### ISSUE TITLE
Data type space

### ISSUE THREAD

**Issue by HichamAbderrahim** [CleverChuk/MipsIde-bug-track#1]
I try to recive msg from user in mips when I set in data party Y:.space 100 and in text party  li $v0,8 and li $a1,50 and la $a0,y he say to me unkown data type: space ....
There is any solution pleas

**Comment by cleverchuk** [comment]
The current implementation doesn’t support space storage class. It’ll be added in later releases. I’ll leave the issue open until it’s added.
Currently support:
- asciiz 
- word

**Comment by cleverchuk** [comment]
Resolved [v2.4.3](https://play.google.com/store/apps/details?id=com.whatismips.mipside)
