### ISSUE TITLE
Save issue

### ISSUE THREAD

**Issue by JeanMark1986** [CleverChuk/MipsIde-bug-track#2]
Hello, I am responding to your request. So I guess I'll just describe what I did. I saved four .asm files using the "save as" button: Test1.asm, Test2.asm, Test3.asm, Test4.asm. After writing different syntax for each file, and saving my progress, I proceeded to open each file individually to see if they were in fact saved; unfortunately, they were not; I was kept on the same screen each time I tried to opening a new file. I then force stopped the app to see if it just froze, upon restarting the App again, I found that all four files were not saved successfully. I am new to MIPs Assembly Language, so perhaps I may have not properly titled my .asm files? If that is true, I am sorry for the confusion. Thanks for making this App.

**Comment by cleverchuk** [comment]
@JeanMark1986 Thanks mate. I will look this and let you know.

**Comment by cleverchuk** [comment]
@JeanMark1986 Which android version are you running?

**Comment by cleverchuk** [comment]
Fixed in version 3.5.3

**Comment by cleverchuk** [comment]
Deployed

**Comment by JeanMark1986** [comment]
Hi, sorry for the late reply. Thank you so much!! -Art

Name: Arthur Hernaez

Cell: 650 521 6392

www.linkedin.com/in/artyhernaez/

https://www.facebook.com/arthur.hernaez

http://364fc9c09adf.ngrok.io/My.Portfolio.html

**Comment by cleverchuk** [comment]
You're welcome mate. Thanks for reporting this bug! We're grateful for users like you!
