### ISSUE TITLE
Design issue with dark theme and action bar icon colors

### ISSUE THREAD

**Issue by avipars** [CleverChuk/MipsIde-bug-track#3]
While using your dark theme, the action bar icons feel like they disappear due to the lack of contrast... I emailed you but I will put my code recs. here , maybe it can help other devs too! 

Example:

In a drawable.xml icon

<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="24.0"
    android:viewportWidth="24.0">
    <path
        android:fillColor="?attr/iconColor"
        android:pathData="M22,3L7,3c-0.69,0 -1.23,0.35 -1.59,0.88L0,12l5.41,8.11c0.36,0.53 0.9,0.89 1.59,0.89h15c1.1,0 2,-0.9 2,-2L24,5c0,-1.1 -0.9,-2 -2,-2zM19,15.59L17.59,17 14,13.41 10.41,17 9,15.59 12.59,12 9,8.41 10.41,7 14,10.59 17.59,7 19,8.41 15.41,12 19,15.59z" />
</vector>

res/values/attrs.xml

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="AppTheme">
        <attr name="iconColor" format="color" />
        <attr name="textColor" format="color" />
        <attr name="menuColor" format="color" />
        <attr name="backSpaceColor" format="color" />
        <attr name="iconPlaceholder" format="integer" />
    </declare-styleable>
</resources>

And then you can differentiate based on themes

Now in styles.xml

    
    <style name="AppThemeDay" parent="Theme.MaterialComponents.Light.Bridge">
        <item name="colorPrimary">@color/colorWhite</item>
        <item name="colorPrimaryDark">@color/colorWhite</item>
        <item name="colorAccent">@color/colorPrimaryDark</item>
        <item name="android:colorBackground">@color/colorWhite</item>
        <item name="android:windowLightStatusBar" tools:targetApi="23">true</item>
        <item name="android:statusBarColor">@android:color/white</item>
        <item name="android:actionBarStyle">@style/MyActionBarStyle</item>
        <item name="menuColor">@color/colorPrimaryDark</item>
        <item name="iconColor">@color/colorPrimaryDark</item>
        <item name="textColor">@color/colorPrimaryDark</item>
        <item name="backSpaceColor">@color/colorPrimaryDark</item>
    </style>

    
    <style name="AppThemeDark" parent="Theme.MaterialComponents.Bridge">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">?android:colorBackground</item>
        <item name="textColor">@color/colorWhite</item>
        <item name="iconColor">@color/colorWhite</item>
        <item name="backSpaceColor">@color/colorWhite</item>
        <item name="menuColor">@color/colorWhite</item>
    </style>

    
    <style name="AppThemeAMOLED" parent="Theme.MaterialComponents.Bridge">
        <item name="colorPrimary">@color/black</item>
        <item name="colorPrimaryDark">@color/black</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:colorBackground">@color/black</item>
        <item name="iconColor">@color/colorWhite</item>
        <item name="textColor">@color/colorWhite</item>
        <item name="backSpaceColor">@color/colorWhite</item>
        <item name="menuColor">@color/colorWhite</item>
    </style>

Hope it helps

**Comment by cleverchuk** [comment]
Please can you provide a screenshot of what the low contrast look like?

**Comment by avipars** [comment]
![image](https://user-images.githubusercontent.com/5733247/179183681-b7ac3595-59a8-423f-9b71-ddd7eb42efa3.png)


It just involves changing the theme to the dark one


I was using grayscale on my phone which makes it look even closer in color

**Comment by cleverchuk** [comment]
Gotcha, thanks.

**Comment by cleverchuk** [comment]
Addressed in version: `4.2.5`. Should be available for download shortly.
